// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYqIIOhMZwnhjjXuSf8T-s-yy-A8gUBX4',
    appId: '1:566995700842:web:3d238042632bcd142b0e13',
    messagingSenderId: '566995700842',
    projectId: 'runstat-57f99',
    authDomain: 'runstat-57f99.firebaseapp.com',
    storageBucket: 'runstat-57f99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEf0P48xVZACrJLYIYcqj-hc0NNo3pB80',
    appId: '1:566995700842:android:0d17b4c018c38d342b0e13',
    messagingSenderId: '566995700842',
    projectId: 'runstat-57f99',
    storageBucket: 'runstat-57f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGjJrs63roOUd6Pg-hpCiS6Eag5wxNdw',
    appId: '1:566995700842:ios:9cfe9f424a6a502e2b0e13',
    messagingSenderId: '566995700842',
    projectId: 'runstat-57f99',
    storageBucket: 'runstat-57f99.appspot.com',
    iosBundleId: 'com.berkeozkul.runstat.runstat',
  );

}